name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: my_env
          auto-activate-base: false

      - name: Install dependencies from environment.yml
        run: conda env update --file environment.yml --name my_env

      - name: Add PREDICT to PYTHONPATH
        run: |
          echo "PYTHONPATH=$env:PYTHONPATH;$($PWD.Path)/PREDICT" >> $env:GITHUB_ENV

      - name: Test with pytest
        run: conda run -n my_env pytest tests/

  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: my_env
          auto-activate-base: false

      - name: Install dependencies from environment.yml
        run: conda env update --file environment.yml --name my_env

      - name: Add PREDICT to PYTHONPATH
        run: |
          echo "PYTHONPATH=$PYTHONPATH:$PWD/PREDICT" >> $GITHUB_ENV

      - name: Test with pytest
        run: conda run -n my_env pytest tests/